---
version: '3'

services:
  service-auth-provider-api:
    image: docker.artifactory.reform.hmcts.net/auth/service-auth-provider-api:latest
    healthcheck:
      disable: true
    ports:
      - 4502:8080
    environment:
      - 'SPRING_APPLICATION_JSON={
          "auth.provider.service.testing-support.enabled" : true,
          "auth.provider.service.server.jwtKey" : "wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==",
          "auth.provider.service.server.microserviceKeys.sscs" : "AAAAAAAAAAAAAAAA",
          "auth.provider.service.server.microserviceKeys.em_gw" : "AAAAAAAAAAAAAAAA"
      }'
