package uk.gov.hmcts.reform.divorce.casemaintenanceservice.domain.model;

import lombok.AllArgsConstructor;
import lombok.Getter;

import java.util.Arrays;
import java.util.stream.Stream;

@AllArgsConstructor
@Getter
public enum AmendCaseRemovedProps {
    // These values are specifically for Amend Petition workflow, NOT for general usage
    D8caseReference("D8caseReference"),
    createdDate("createdDate"),
    D8ReasonForDivorce("D8ReasonForDivorce"),
    D8DerivedStatementOfCase("D8DerivedStatementOfCase"),
    D8RejectStatementOfCase("D8RejectStatementOfCase"),
    D8ReasonForDivorceBehaviourDetails("D8ReasonForDivorceBehaviourDetails"),
    D8ReasonForDivorceDesertionDetails("D8ReasonForDivorceDesertionDetails"),
    D8ReasonForDivorceSeperationDate("D8ReasonForDivorceSeperationDate"),
    D8ReasonForDivorceAdultery3rdPartyFName("D8ReasonForDivorceAdultery3rdPartyFName"),
    D8ReasonForDivorceAdultery3rdPartyLName("D8ReasonForDivorceAdultery3rdPartyLName"),
    D8DerivedReasonForDivorceAdultery3dPtyNm("D8DerivedReasonForDivorceAdultery3dPtyNm"),
    D8ReasonForDivorceAdulteryDetails("D8ReasonForDivorceAdulteryDetails"),
    D8ReasonForDivorceAdulteryKnowWhen("D8ReasonForDivorceAdulteryKnowWhen"),
    D8ReasonForDivorceAdulteryWishToName("D8ReasonForDivorceAdulteryWishToName"),
    D8ReasonForDivorceAdulteryKnowWhere("D8ReasonForDivorceAdulteryKnowWhere"),
    D8ReasonForDivorceAdulteryWhereDetails("D8ReasonForDivorceAdulteryWhereDetails"),
    D8ReasonForDivorceAdulteryWhenDetails("D8ReasonForDivorceAdulteryWhenDetails"),
    D8ReasonForDivorceAdulteryIsNamed("D8ReasonForDivorceAdulteryIsNamed"),
    D8ReasonForDivorceAdultery3rdAddress("D8ReasonForDivorceAdultery3rdAddress"),
    D8DerivedReasonForDivorceAdultery3rdAddr("D8DerivedReasonForDivorceAdultery3rdAddr"),
    D8HelpWithFeesNeedHelp("D8HelpWithFeesNeedHelp"),
    D8HelpWithFeesAppliedForFees("D8HelpWithFeesAppliedForFees"),
    D8HelpWithFeesReferenceNumber("D8HelpWithFeesReferenceNumber"),
    D8PaymentMethod("D8PaymentMethod"),
    Payments("Payments"),
    D8StatementOfTruth("D8StatementOfTruth"),
    D8DivorceUnit("D8DivorceUnit"),
    D8ReasonForDivorceHasMarriage("D8ReasonForDivorceHasMarriage"),
    D8ReasonForDivorceShowAdultery("D8ReasonForDivorceShowAdultery"),
    D8ReasonForDivorceShowUnreasonableBehavi("D8ReasonForDivorceShowUnreasonableBehavi"),
    D8ReasonForDivorceShowTwoYearsSeparation("D8ReasonForDivorceShowTwoYearsSeparation"),
    D8ReasonForDivorceShowFiveYearsSeparatio("D8ReasonForDivorceShowFiveYearsSeparatio"),
    D8ReasonForDivorceShowDesertion("D8ReasonForDivorceShowDesertion"),
    D8ReasonForDivorceLimitReasons("D8ReasonForDivorceLimitReasons"),
    D8ReasonForDivorceEnableAdultery("D8ReasonForDivorceEnableAdultery"),
    D8ReasonForDivorceDesertionAlright("D8ReasonForDivorceDesertionAlright"),
    D8ReasonForDivorceClaiming5YearSeparatio("D8ReasonForDivorceClaiming5YearSeparatio"),
    D8ReasonForDivorceClaimingAdultery("D8ReasonForDivorceClaimingAdultery"),
    D8ReasonForDivorceSeperationDay("D8ReasonForDivorceSeperationDay"),
    D8ReasonForDivorceSeperationMonth("D8ReasonForDivorceSeperationMonth"),
    D8ReasonForDivorceSeperationYear("D8ReasonForDivorceSeperationYear"),
    D8ReasonForDivorceSeperation("D8ReasonForDivorceSeperation"),
    D8ReasonForDivorceSeperationIsSameOrAftr("D8ReasonForDivorceSeperationIsSameOrAftr"),
    D8ReasonForDivorceSeperationInFuture("D8ReasonForDivorceSeperationInFuture"),
    D8ReasonForDivorceSeperationBeforeMarria("D8ReasonForDivorceSeperationBeforeMarria"),
    D8ReasonForDivorceDesertionDay("D8ReasonForDivorceDesertionDay"),
    D8ReasonForDivorceDesertionMonth("D8ReasonForDivorceDesertionMonth"),
    D8ReasonForDivorceDesertionYear("D8ReasonForDivorceDesertionYear"),
    D8ReasonForDivorceDesertionBeforeMarriag("D8ReasonForDivorceDesertionBeforeMarriag"),
    D8ReasonForDivorceDesertionInFuture("D8ReasonForDivorceDesertionInFuture"),
    D8ReasonForDivorceDesertion("D8ReasonForDivorceDesertion"),
    D8ReasonForDivorce2YearSepConsentGiven("D8ReasonForDivorce2YearSepConsentGiven"),
    D8MentalSeparationDate("D8MentalSeparationDate"),
    D8PhysicalSeparationDate("D8PhysicalSeparationDate"),
    D8SeparationTimeTogetherPermitted("D8SeparationTimeTogetherPermitted"),
    D8LivedTogetherMoreTimeThanPermitted("D8LivedTogetherMoreTimeThanPermitted"),
    D8LivedApartSinceSeparation("D8LivedApartSinceSeparation"),
    D8LivedApartSinceDesertion("D8LivedApartSinceDesertion"),
    D8DesertionTimeTogetherPermitted("D8DesertionTimeTogetherPermitted"),
    D8LivedTogetherMoreTimeThanPermittedDesert("D8LivedTogetherMoreTimeThanPermittedDesert"),
    SolSOCAdulteryHaveTheyLivedTogetherfor6MonthsSinceAdulteryWhenDetails(
        "SolSOCAdulteryHaveTheyLivedTogetherfor6MonthsSinceAdulteryWhenDetails"),
    SolSOCDesertionLivedSeperateSinceDate("SolSOCDesertionLivedSeperateSinceDate"),
    SeparationLivedTogetherAsCoupleAgain("SeparationLivedTogetherAsCoupleAgain"),
    SeparationLivedTogetherAsCoupleAgainDetails("SeparationLivedTogetherAsCoupleAgainDetails"),
    solApplicationFeeOrderSummary("solApplicationFeeOrderSummary"),
    FeeAccountReference("FeeAccountReference"),
    PetitionerSolicitorToEffectService("PetitionerSolicitorToEffectService"),
    solSignStatementofTruth("solSignStatementofTruth"),
    respondentSolicitorReference("respondentSolicitorReference"),
    dueDate("dueDate"),
    AosLetterHolderId("AosLetterHolderId"),
    ReceivedAOSfromResp("ReceivedAOSfromResp"),
    ReceivedAOSfromRespDate("ReceivedAOSfromRespDate"),
    ReceivedAnswerFromResp("ReceivedAnswerFromResp"),
    ReceivedAnswerFromRespDate("ReceivedAnswerFromRespDate"),
    RespConfirmReadPetition("RespConfirmReadPetition"),
    RespAdmitOrConsentToFact("RespAdmitOrConsentToFact"),
    RespDefendsDivorce("RespDefendsDivorce"),
    RespJurisdictionAgree("RespJurisdictionAgree"),
    RespJurisdictionDisagreeReason("RespJurisdictionDisagreeReason"),
    RespJurisdictionRespCountryOfResidence("RespJurisdictionRespCountryOfResidence"),
    RespLegalProceedingsExist("RespLegalProceedingsExist"),
    RespLegalProceedingsDescription("RespLegalProceedingsDescription"),
    RespAgreeToCosts("RespAgreeToCosts"),
    RespCostsAmount("RespCostsAmount"),
    RespCostsReason("RespCostsReason"),
    RespEmailAddress("RespEmailAddress"),
    RespPhoneNumber("RespPhoneNumber"),
    RespStatementOfTruth("RespStatementOfTruth"),
    RespConsentToEmail("RespConsentToEmail"),
    RespConsiderFinancialSituation("RespConsiderFinancialSituation"),
    RespHardshipDefenseResponse("RespHardshipDefenseResponse"),
    RespHardshipDescription("RespHardshipDescription"),
    RespContactMethodIsDigital("RespContactMethodIsDigital"),
    DNApplicationSubmittedDate("DNApplicationSubmittedDate"),
    PetitionChangedDetailsDN("PetitionChangedDetailsDN"),
    ConfirmPetitionDN("ConfirmPetitionDN"),
    DivorceCostsOptionDN("DivorceCostsOptionDN"),
    CostsDifferentDetails("CostsDifferentDetails"),
    DocumentsUploadedDN("DocumentsUploadedDN"),
    statementOfTruthDN("statementOfTruthDN"),
    AlternativeRespCorrAddress("AlternativeRespCorrAddress"),
    AdulteryLifeIntolerable("AdulteryLifeIntolerable"),
    AdulteryDateFoundOut("AdulteryDateFoundOut"),
    AdulteryLivedApartSinceEventDN("AdulteryLivedApartSinceEventDN"),
    AdulteryTimeLivedTogetherDetailsDN("AdulteryTimeLivedTogetherDetailsDN"),
    BehaviourStillHappeningDN("BehaviourStillHappeningDN"),
    BehaviourMostRecentIncidentDateDN("BehaviourMostRecentIncidentDateDN"),
    BehaviourLivedApartSinceEventDN("BehaviourLivedApartSinceEventDN"),
    BehaviourTimeLivedTogetherDetailsDN("BehaviourTimeLivedTogetherDetailsDN"),
    DesertionLivedApartSinceEventDN("DesertionLivedApartSinceEventDN"),
    DesertionTimeLivedTogetherDetailsDN("DesertionTimeLivedTogetherDetailsDN"),
    SeparationLivedApartSinceEventDN("SeparationLivedApartSinceEventDN"),
    SeparationTimeLivedTogetherDetailsDN("SeparationTimeLivedTogetherDetailsDN"),
    PaymentHistory("PaymentHistory"),
    IssueDate("IssueDate"),
    PermittedDecreeNisiReason("PermittedDecreeNisiReason"),
    DNApplyForDecreeNisi("DNApplyForDecreeNisi"),
    PreviousReasonsForDivorce("PreviousReasonsForDivorce"),
    D8DocumentsGenerated("D8DocumentsGenerated"),
    D8DivorceCostsClaim("D8DivorceCostsClaim"),
    D8DivorceClaimFrom("D8DivorceClaimFrom"),
    D8SeparationReferenceDate("D8SeparationReferenceDate");

    private final String value;

    public static Stream<String> getProps() {
        return Arrays.stream(AmendCaseRemovedProps.values()).map(AmendCaseRemovedProps::getValue);
    }
}
